### ISSUE TITLE
Wrong output filename causes workflow to fail

### ISSUE THREAD

**Issue by geniass** [gatk-workflows/seq-format-conversion#1]
The output file generated by [the Java command](https://github.com/gatk-workflows/seq-format-conversion/blob/03f84a60c12a50d2045cf7a4131f1eaa169fead8/paired-fastq-to-unmapped-bam.wdl#L78) produces a file with the extension `.bam` (note not `.unmapped.bam`)

However the workflow output file [expects](https://github.com/gatk-workflows/seq-format-conversion/blob/03f84a60c12a50d2045cf7a4131f1eaa169fead8/paired-fastq-to-unmapped-bam.wdl#L94) a file with extension `.unmapped.bam`. This causes the workflow to fail since it can't find the output file.

**Comment by bshifaw** [comment]
Fixed. Thanks!
