### ISSUE TITLE
How can I specify "TMP_DIR=/path/" when processing large files in Terra?

### ISSUE THREAD

**Issue by sahuno** [gatk-workflows/seq-format-conversion#7]
Hello Broad, 

I'm generating .ubams from large bam files (>30GB) using [bam-to-unmapped-bams.wd](https://github.com/gatk-workflows/seq-format-conversion/blob/master/bam-to-unmapped-bams.wdl) in Terra 

Please how can i specify the `TMP_DIR=/path/for/temp/` for my `RevertSam`/`SortSam` in order to efficiently complete this task? as suggested in the [Broad GATK discussion forum](https://gatkforums.broadinstitute.org/gatk/discussion/6484/how-to-generate-an-unmapped-bam-from-fastq-or-aligned-bam)

Thanks for your help!

**Comment by bshifaw** [comment]
You would need to edit the WDL to add TMP_DIR in the command. 

```
    ${gatk_path} --java-options "-Xmx${command_mem_gb}g" \
    RevertSam \
    --INPUT ${input_bam} \
    --OUTPUT $PWD \
    --OUTPUT_BY_READGROUP true \
    --VALIDATION_STRINGENCY LENIENT \
    --ATTRIBUTE_TO_CLEAR FT \
    --ATTRIBUTE_TO_CLEAR CO \
    --TMP_DIR=/path/for/temp/ \
    --SORT_ORDER coordinate
```
